### ISSUE TITLE
Broken damage calculation for Leon's Clover of Honour

### ISSUE THREAD

**Issue by cdbfoster** [Leimi/nautsbuilder#22]
Since the change in the behavior of the item from every third hit to every second hit, selecting Clover of Honour by itself results in NaN > NaN > 8 damage.

**Comment by D4RKONION** [comment]
I'm working on this atm, however, I've changed the corresponding spreadsheet cell to say "2nd Hit Damage: +40" instead of "Damage: +0 > +40" and I can't pull this new info into the app. 

Is there a way to change this info locally or does it have to be pulled in by someone with access everytime? If so, would it be possible to gain that access so I don't have to annoy you for it every time I try to fix something?

**Comment by r0estir0bbe** [comment]
> Is there a way to change this info locally or does it have to be pulled in by someone with access everytime? If so, would it be possible to gain that access so I don't have to annoy you for it every time I try to fix something?

Yes! Open [`localhost/spreadsheet`](http://localhost/spreadsheet) and hit `Ok, let's go` to update your local data. The online version (http://nautsbuilder.com/spreadsheet) is password-protected.

> I'm working on this atm, however, I've changed the corresponding spreadsheet cell to say "2nd Hit Damage: +40" instead of "Damage: +0 > +40" and I can't pull this new info into the app. 

Sadly, this won't fix the issue as well. Currently, the code in [`skill.js`](https://github.com/Leimi/nautsbuilder/blob/master/js/nautsbuilder/data/skill.js#L399) uses the damage from the (unset) effect `3rd hit damage` which is wrong.

I will quickly fix this by adjusting the code section inside `skill.js`, but in the future I would like to avoid upgrade-specific code inside Nautsbuilder as much as possible. And Nautsbuilder should be able to support Clover of Honour natively. For that, I can create a new issue.
